export const SERVICES = {
  USER_SERVICE: 'USER_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  CHECK_IN_SERVICE: 'CHECK_IN_SERVICE',
  CONTACT_SERVICE: 'CONTACT_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  MAIL_SERVICE: 'MAIL_SERVICE',
};

export const SERVICE_PORTS = {
  USER_SERVICE: parseInt(process.env.USER_SERVICE_PORT ?? '3001', 10),
  AUTH_SERVICE: parseInt(process.env.AUTH_SERVICE_PORT ?? '3002', 10),
  CHECK_IN_SERVICE: parseInt(process.env.CHECK_IN_SERVICE_PORT ?? '3003', 10),
  CONTACT_SERVICE: parseInt(process.env.CONTACT_SERVICE_PORT ?? '3004', 10),
  NOTIFICATION_SERVICE: parseInt(process.env.NOTIFICATION_SERVICE_PORT ?? '3005', 10),
  MAIL_SERVICE: parseInt(process.env.MAIL_SERVICE_PORT ?? '3006', 10),
};
